### PR TITLE
Pr 5246

### PR DESCRIPTION
**Pull request by pv**
Fix a couple of things:

- Namespace where tests are run in should only have `import numpy as np`; separate it from check evaluation namespace
- Close matplotlib figures between docstrings (maybe helps with the matplotlib issue?)
- Style issue with mutable default args

### CODE REVIEW

**Comment by ev-br** [comment]
Thanks!

**Comment by ev-br** [comment]
> Namespace where tests are run in should only have import numpy as np; separate it from check evaluation namespace

So the idea is to not allow direct copy-pasting in the tutorial files?

**Comment by pv** [comment]
I'm not sure what you mean --- it's just that the tutorials did
```
from scipy.special import quad
res = quad(lambda x: 1/(x**2 +1), 0, inf)
```
which is an error, because `inf` wasn't imported anywhere.

**Comment by ev-br** [comment]
Yup, I see now.

**Pull request merged**
